name: "fs: ci"

on:
  push:
    branches: [ master, zpp_fs ]
  pull_request:
    branches: [ master, zpp_fs, fs-* ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: scylladb/seastar-toolchain:latest

    strategy:
      matrix:
        mode: [release]
        dialect: [c++17] # TODO: add c++20

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Cache build
        id: cache
        uses: actions/cache@v1
        with:
          path: build/${{ matrix.mode }}
          key: ${{ runner.os }}-build-${{ matrix.mode }}-fs

      - name: Set ENV variables
        run: echo "::set-env name=SEASTAR_FS_TESTS::$(echo tests/unit/fs_*_test.cc | sed 's/\.cc//g')"

      - name: Configure
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./configure.py --mode=${{ matrix.mode }} --c++-dialect ${{ matrix.dialect }} --enable-experimental-fs

      - name: Change mtime # We are going to rebuild only fs files
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          OLDEST_MTIME=$(find build/${{ matrix.mode }} -type f -printf '%.10T@\n' | sort | head -n 1)
          export OLDEST_MTIME=$((OLDEST_MTIME-1))
          echo $OLDEST_MTIME
          find $(ls -1 | grep -v '^build$') -type f -exec touch -c -m -d "@$OLDEST_MTIME" {} \;
          find $(ls -1 | grep -v '^build$') | grep -P '/fs(/|_)|CMakeLists.txt' | xargs touch -c -m

      - name: Build
        run: ninja -C build/${{ matrix.mode }} ${{ env.SEASTAR_FS_TESTS }}

      - name: Tests
        run: | # TODO: add similar logic to test.py
          for test in ${{ env.SEASTAR_FS_TESTS }}; do
          echo -e "\033[1;36m$test\033[m"
          build/${{ matrix.mode }}/$test
          done
