name: "fs: ci"

on:
  push:
    branches: [ zpp_fs ]
  pull_request:
    branches: [ zpp_fs, fs-* ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: scylladb/seastar-toolchain:latest

    strategy:
      matrix:
        mode: [release]
        dialect: [c++17] # TODO: add c++20

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set ENV variables
        run: echo "::set-env name=SEASTAR_FS_TESTS::$(echo tests/unit/fs_*_test.cc | sed 's/\.cc//g')"

      - name: Configure
        run: ./configure.py --mode=${{ matrix.mode }} --c++-dialect ${{ matrix.dialect }} --enable-experimental-fs

      - name: Build
        run: ninja -C build/${{ matrix.mode }} ${{ env.SEASTAR_FS_TESTS }}

      - name: Tests
        run: | # TODO: add similar logic to test.py
          for test in ${{ env.SEASTAR_FS_TESTS }}; do
          echo -e "\033[1;36m$test\033[m"
          build/${{ matrix.mode }}/$test
          done
